# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:50
from __future__ import unicode_literals

from django.db import migrations


def add_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    from users.models import GROUP_ADMIN_PK, GROUP_AGENT_PK, GROUP_MANAGER_PK
    Group.objects.create(pk=GROUP_ADMIN_PK, name='Администратор')
    Group.objects.create(pk=GROUP_MANAGER_PK, name='Менеджер')
    Group.objects.create(pk=GROUP_AGENT_PK, name='Агент')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
