# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170120_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='price_e',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена кат. E'),
        ),
    ]
