# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_price_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='limit_per_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Лимит на день'),
        ),
    ]
