# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_price_e'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('can_create_admin', 'Может создавать администраторов'), ('can_create_agent', 'Может создавать агентов'), ('can_create_manager', 'Может создавать менеджеров'), ('can_move_all_child', 'Может перемещать агентов'))},
        ),
    ]
