# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170214_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrintSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('org_title', models.CharField(max_length=255, verbose_name='Организация')),
                ('reg_number', models.CharField(max_length=255, verbose_name='Рег. номер')),
                ('point_address', models.CharField(max_length=255, verbose_name='Адрес пункта ТО')),
                ('expert_name', models.CharField(max_length=255, verbose_name='ФИО эксперта полностью')),
                ('stamp', models.ImageField(blank=True, height_field=455, null=True, upload_to='media/stamp/', verbose_name='Печать', width_field=455)),
            ],
        ),
    ]
