# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170222_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_confirm_key',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Ключ подтверждения почты'),
        ),
    ]
