# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170222_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('fio', 'username'), 'permissions': (('can_create_admin', 'Может создавать администраторов'), ('can_create_agent', 'Может создавать агентов'), ('can_create_manager', 'Может создавать менеджеров'), ('can_move_all_child', 'Может перемещать агентов'))},
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_confirm_test',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для подтверждения'),
        ),
    ]
