# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170226_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('fio', 'username'), 'permissions': (('can_create_admin', 'Может создавать администраторов'), ('can_create_agent', 'Может создавать агентов'), ('can_create_manager', 'Может создавать менеджеров'), ('can_move_child', 'Может перемещать агентов'), ('can_crud_child', 'Может редактировать своих агентов'), ('can_crud_all_child', 'Может редактировать своих агентов и агентов агентов'), ('can_change_user_child_print_settings', 'Может редактировать шапки агентов'))},
        ),
    ]
