# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20170227_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprintsettings',
            name='is_only_me',
            field=models.BooleanField(default=False, verbose_name='Только для меня'),
        ),
    ]
