# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprintsettings_is_only_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='use_only_self_stantions',
            field=models.BooleanField(default=False, verbose_name='Может использовать только свои станции'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City', verbose_name='Город'),
        ),
    ]
