# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170301_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='notification_settings',
            field=models.CharField(blank=True, choices=[(None, 'Без уведомлений'), ('weekly', 'Раз в неделю'), ('half_monthly', '2 раза в месяц'), ('monthly', 'Раз в месяц')], max_length=12, null=True, verbose_name='Уведомления об оплате'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='notification_weekly_day',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='День недели'),
        ),
    ]
