# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170302_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион'),
        ),
    ]
