# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20170306_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='can_delete_card',
            field=models.BooleanField(default=False, verbose_name='Может удалять заявки'),
        ),
    ]
