# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170315_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_https',
            field=models.BooleanField(default=True, help_text='При проблемах доступа к сайту, отключите эту настройку.', verbose_name='Включить защищеннное соединение (HTTPS)'),
        ),
    ]
