# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170326_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='order_type',
        ),
        migrations.AddField(
            model_name='myuser',
            name='stantion_order_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Равномерно'), (2, 'По очереди')], default=1, verbose_name='Тип очереди для станций'),
        ),
    ]
