# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0015_auto_20170213_1809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.IntegerField(choices=[(1, 'Создана'), (2, 'В процессе'), (3, 'Исполнена')], default=1, verbose_name='Статус')),
                ('action', models.IntegerField(choices=[(1, 'Пополнение баланса'), (2, 'Списание за заявку')], verbose_name='Действие')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Стоимость')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
