# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20170223_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.IntegerField(choices=[(1, 'Пополнение баланса'), (2, 'Списание за заявку'), (3, 'Дубликат заявки')], verbose_name='Действие'),
        ),
    ]
