# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_date', models.DateField(verbose_name='Дата договора')),
                ('agreement_number', models.CharField(max_length=255, verbose_name='Номер договора')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('seller_user_last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('seller_user_first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('seller_user_middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('seller_birthday', models.DateField(verbose_name='Дата рождения')),
                ('seller_passport_seria', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('seller_passport_number', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('seller_passport_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('seller_passport_org', models.TextField(verbose_name='Кем выдан паспорт')),
                ('seller_address_reg', models.TextField(verbose_name='Адрес регистрации')),
                ('seller_address_fact', models.TextField(verbose_name='Фактический адрес')),
                ('is_repr', models.BooleanField(default=False, verbose_name='Продажа через представителя')),
                ('repr_user_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('repr_user_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('repr_user_middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('repr_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('repr_document_number', models.CharField(blank=True, max_length=255, verbose_name='Номер доверенности')),
                ('repr_document_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи доверенности')),
                ('repr_document_verified_by', models.TextField(blank=True, null=True, verbose_name='Кем заверена')),
                ('repr_passport_seria', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия паспорта')),
                ('repr_passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер паспорта')),
                ('repr_passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('repr_passport_org', models.TextField(blank=True, null=True, verbose_name='Кем выдан паспорт')),
                ('repr_address_reg', models.TextField(blank=True, null=True, verbose_name='Адрес регистрации')),
                ('repr_address_fact', models.TextField(blank=True, null=True, verbose_name='Фактический адрес')),
                ('buyer_user_last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('buyer_user_first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('buyer_user_middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('buyer_birthday', models.DateField(verbose_name='Дата рождения')),
                ('buyer_passport_seria', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('buyer_passport_number', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('buyer_passport_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('buyer_passport_org', models.TextField(verbose_name='Кем выдан паспорт')),
                ('buyer_address_reg', models.TextField(verbose_name='Адрес регистрации')),
                ('buyer_address_fact', models.TextField(verbose_name='Фактический адрес')),
                ('ts_vin', models.CharField(blank=True, help_text='Если отсутствует, то не заполняется', max_length=255, verbose_name='VIN')),
                ('ts_body_num', models.CharField(blank=True, max_length=255, verbose_name='Номер кузова')),
                ('ts_frame_num', models.CharField(blank=True, max_length=255, verbose_name='Номер рамы (шасси)')),
                ('ts_mark', models.CharField(max_length=255, verbose_name='Марка')),
                ('ts_model', models.CharField(max_length=255, verbose_name='Модель')),
                ('ts_year', models.IntegerField(verbose_name='Год выпуска')),
                ('ts_color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('ts_reg_num', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('ts_engine_num', models.CharField(max_length=255, verbose_name='Номер двигателя')),
                ('pts_serial', models.CharField(max_length=255, verbose_name='Серия')),
                ('pts_num', models.CharField(max_length=255, verbose_name='Номер')),
                ('pts_issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('pts_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('srts_serial', models.CharField(max_length=255, verbose_name='Серия')),
                ('srts_num', models.CharField(max_length=255, verbose_name='Номер')),
                ('srts_issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('srts_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
