# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_auto_20170225_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='srts_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='srts_issued_date',
            field=models.DateField(blank=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='srts_num',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='srts_serial',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия'),
        ),
    ]
