# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_messages', '0002_auto_20170126_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-pk',), 'permissions': (('can_send_message_child', 'Может отправлять сообщения своим агентам'), ('can_send_message_all_child', 'Может отправлять сообщения всем своим агентам и агентам агентов'))},
        ),
    ]
