# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_messages', '0004_auto_20170223_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_html',
            field=models.BooleanField(default=False, verbose_name='Html'),
        ),
    ]
