# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_messages', '0005_message_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pay_alert',
            field=models.BooleanField(default=False, verbose_name='Оповещение об оплате'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pay_alert_hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть оповещение об оплате'),
        ),
    ]
