# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stantions', '0002_auto_20170209_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stantion',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelManagers(
            name='stantion',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='stantion',
            name='is_available_for_all_users',
            field=models.BooleanField(default=False, verbose_name='Доступно для всех'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='requests_created',
            field=models.IntegerField(blank=True, default=0, verbose_name='Создано за день'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
