# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0003_auto_20170211_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stantion',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='stantion',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключ для API'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='interface',
            field=models.CharField(blank=True, choices=[('eaisto', 'ЕАИСТО')], max_length=255, verbose_name='Интерфейс'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='is_available_for_child',
            field=models.BooleanField(default=False, verbose_name='Доступно для потомков'),
        ),
    ]
