# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0005_auto_20170222_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stantion',
            old_name='user',
            new_name='users',
        ),
    ]
