# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0008_auto_20170301_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='interface',
            field=models.CharField(blank=True, choices=[('eaisto', 'ЕАИСТО')], default='eaisto', max_length=255, verbose_name='Интерфейс'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.City', verbose_name='Город оператора'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='interface',
            field=models.CharField(blank=True, choices=[('eaisto', 'ЕАИСТО')], default='eaisto', max_length=255, verbose_name='Интерфейс'),
        ),
    ]
