# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0010_auto_20170301_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stantion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City', verbose_name='Город оператора'),
        ),
    ]
