# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0013_stantion_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='stantion',
            name='available_a',
            field=models.BooleanField(default=True, verbose_name='Доступна кат. А'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='available_b',
            field=models.BooleanField(default=True, verbose_name='Доступна кат. B'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='available_c',
            field=models.BooleanField(default=True, verbose_name='Доступна кат. С'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='available_d',
            field=models.BooleanField(default=True, verbose_name='Доступна кат. D'),
        ),
        migrations.AddField(
            model_name='stantion',
            name='available_trailer',
            field=models.BooleanField(default=True, verbose_name='Доступна кат. прицеп'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='eaisto_password',
            field=models.CharField(blank=True, help_text='Если оставить пустым, то старый пароль не изменится.', max_length=255, verbose_name='Пароль ЕАИСТО'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='address',
            field=models.CharField(blank=True, help_text='Укажите тут улицу, дом и корпус при наличии.', max_length=255, verbose_name='Адрес оператора'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='daily_limit',
            field=models.IntegerField(help_text='Колличество карт, которое возможно сделать за один день.', verbose_name='Дневной Лимит'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='eaisto_password',
            field=models.CharField(blank=True, help_text='Если оставить пустым, то старый пароль не изменится.', max_length=255, verbose_name='Пароль ЕАИСТО'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='order',
            field=models.IntegerField(help_text='Меньшее значение заполняется в первую очередь.', verbose_name='№ в очереди на заполнение'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='point_address',
            field=models.CharField(blank=True, help_text='Указывать, если отличается от адреса оператора.', max_length=255, verbose_name='Адрес пункта ТО'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='reg_number',
            field=models.CharField(help_text='Регистрационный номер в реестре операторов, состоящий из пяти символов.', max_length=255, verbose_name='Рег. номер'),
        ),
    ]
