# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0014_auto_20170304_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='stantion',
            name='auto_update',
            field=models.BooleanField(default=False, verbose_name='Автоматически обновлять данные'),
        ),
    ]
