# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0015_stantion_auto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='stantion',
            name='freeze_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заморозить станцию до'),
        ),
    ]
