# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0016_stantion_freeze_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='interface',
            field=models.CharField(blank=True, choices=[('eaisto', 'ЕАИСТО'), ('eaisto_online', 'eaisto.online')], default='eaisto', max_length=255, verbose_name='Интерфейс'),
        ),
        migrations.AlterField(
            model_name='stantion',
            name='interface',
            field=models.CharField(blank=True, choices=[('eaisto', 'ЕАИСТО'), ('eaisto_online', 'eaisto.online')], default='eaisto', max_length=255, verbose_name='Интерфейс'),
        ),
    ]
