# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stantions', '0021_auto_20170604_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatoroperatornum',
            name='reg_number',
            field=models.IntegerField(help_text='Регистрационный номер в реестре операторов, состоящий из пяти символов.', verbose_name='Рег. номер'),
        ),
    ]
