# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_send', models.DateTimeField(blank=True, verbose_name='Дата отправки')),
                ('date_done', models.DateTimeField(blank=True, verbose_name='Дата выполнения')),
                ('status', models.IntegerField(choices=[(1, 'Создана'), (2, 'Ожидает отправки'), (3, 'В процессе'), (4, 'Выполнена'), (5, 'Отменена')], verbose_name='Статус')),
                ('diagcard_num', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('user_type', models.IntegerField(choices=[(1, 'Физическое лицо'), (2, 'Юридическое лицо')], default=1, verbose_name='Тип пользователя')),
                ('user_last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('user_first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('user_middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('org_title', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('doc_type', models.IntegerField(choices=[(1, 'СРТС'), (2, 'ПТС')], default=1, verbose_name='Тип документа')),
                ('doc_serial', models.CharField(max_length=255, verbose_name='Серия')),
                ('doc_num', models.CharField(max_length=255, verbose_name='Норме')),
                ('doc_issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('doc_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('ts_category', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'Прицеп')], verbose_name='Категория ТС')),
                ('ts_sub_category', models.IntegerField(verbose_name='Подкатегория ТС')),
                ('ts_reg_num', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный знак')),
                ('ts_vin', models.CharField(blank=True, max_length=255, verbose_name='VIN')),
                ('ts_body_num', models.CharField(blank=True, max_length=255, verbose_name='Номер кузова')),
                ('ts_frame_num', models.CharField(blank=True, max_length=255, verbose_name='Номер рамы (шасси)')),
                ('ts_mark', models.CharField(max_length=255, verbose_name='Марка')),
                ('ts_model', models.CharField(max_length=255, verbose_name='Модель')),
                ('ts_year', models.IntegerField(verbose_name='Год выпуска')),
                ('ts_mass_base', models.IntegerField(verbose_name='Масса без нагрузки')),
                ('ts_mass_max', models.IntegerField(verbose_name='Максимальная масса')),
                ('ts_mileage', models.IntegerField(verbose_name='Пробег')),
                ('ts_fuel_type', models.IntegerField(blank=True, choices=[(1, 'Бензин'), (2, 'Дизель')], verbose_name='Тип топлива')),
                ('ts_brakes_type', models.IntegerField(choices=[(1, 'Гидравлическая'), (2, 'Пневматическая'), (3, 'Комбинированная'), (4, 'Механическая')], verbose_name='Тип тормозной системы')),
                ('ts_taxi', models.BooleanField(default=False, verbose_name='Такси')),
                ('ts_training', models.BooleanField(default=False, verbose_name='Учебная езда')),
                ('ts_dangerous', models.BooleanField(default=False, verbose_name='Опасные грузы')),
                ('ts_dual_fuel', models.IntegerField(blank=True, choices=[(1, 'Пропан-бутан/бензин'), (2, 'Метан/бензин')], verbose_name='Двухтопливная система')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TyreVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='request',
            name='ts_tyre_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.TyreVendor', verbose_name='Марка шин'),
        ),
    ]
