# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20170204_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='request',
            name='doc_num',
            field=models.CharField(max_length=255, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ts_sub_category',
            field=models.IntegerField(blank=True, choices=[(1, 'M1 (легковые до 8-ми пассажирских мест)'), (1, 'N1 (грузовые с максимальной массой не более 3,5 тонн)')], verbose_name='Подкатегория ТС'),
        ),
    ]
