# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20170205_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ts_dual_fuel',
            field=models.IntegerField(blank=True, choices=[(1, 'Пропан-бутан/бензин'), (2, 'Метан/бензин')], null=True, verbose_name='Двухтопливная система'),
        ),
    ]
