# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20170205_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_done',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ts_brakes_type',
            field=models.IntegerField(choices=[(1, 'Гидравлическая'), (2, 'Пневматическая'), (3, 'Комбинированная'), (4, 'Механическая')], null=True, verbose_name='Тип тормозной системы'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ts_fuel_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Бензин'), (2, 'Дизель')], null=True, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ts_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ts_sub_category',
            field=models.IntegerField(blank=True, choices=[(1, 'M1 (легковые до 8-ми пассажирских мест)'), (1, 'N1 (грузовые с максимальной массой не более 3,5 тонн)')], null=True, verbose_name='Подкатегория ТС'),
        ),
    ]
