# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20170205_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('can_view_child', 'Может видеть заявки потомков'), ('can_view_all', 'Может видеть все заявки'))},
        ),
    ]
