# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20170206_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ts_reg_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер'),
        ),
    ]
