# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20170206_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-date_created',), 'permissions': (('can_view_child', 'Может видеть заявки потомков'), ('can_view_all', 'Может видеть все заявки'))},
        ),
    ]
