# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20170208_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
    ]
