# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_request_reg_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reg_num',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регистрациоднный номер'),
        ),
    ]
