# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20170213_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'Выполнена'), (3, 'Отменена')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='requesttasklog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='cards.Request'),
        ),
    ]
