# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20170215_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
    ]
