# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20170222_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ts_tyre_vendor',
            field=models.CharField(max_length=255, verbose_name='Марка шин'),
        ),
    ]
