# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:46
from __future__ import unicode_literals

from django.db import migrations


def add_data(apps, schema_editor):
    TsMark = apps.get_model("cards", "TsMark")

    for mark in ["Acura", "Alfa Romeo", "Alpina", "Aro", "Asia", "Aston Martin", "Audi", "Austin", "Bentley", "BMW",
                 "Brilliance", "Bugatti", "Buick", "BYD", "Cadillac", "Caterham", "ChangFeng", "Chery", "Chevrolet",
                 "Chrysler", "Citroen", "Coggiola", "Dacia", "Dadi", "Daewoo", "Daihatsu", "Daimler", "Derways",
                 "Dodge", "Dong Feng", "Doninvest", "Donkervoort", "Eagle", "FAW", "Ferrari", "Fiat", "Ford", "Geely",
                 "Geo", "GMC", "Great Wall", "Hafei", "Honda", "HuangHai", "Hummer", "Hyundai", "Infiniti",
                 "Iran Khodro", "Isuzu", "JAC", "Jaguar", "Jeep", "Kia", "Koenigsegg", "Lamborghini", "Lancia",
                 "Land Rover", "Landwind", "Lexus", "Lifan", "Lincoln", "Lotus", "Mahindra", "Maruti", "Maserati",
                 "Maybach", "Mazda", "Mercedes-Benz", "Mercury", "Metrocab", "MG", "Microcar", "Mini", "Mitsubishi",
                 "Mitsuoka", "Morgan", "Nissan", "Oldsmobile", "Opel", "Pagani", "Peugeot", "Plymouth", "Pontiac",
                 "Porsche", "Proton", "PUCH", "Renault", "Rolls-Royce", "Rover", "Saab", "Saleen", "Saturn", "Scion",
                 "SEAT", "ShuangHuan", "Skoda", "Smart", "Spyker", "SsangYong", "Subaru", "Suzuki", "Tatra", "Tianma",
                 "Tianye", "Toyota", "Trabant", "TVR", "Vector", "Volkswagen", "Volvo", "Wartburg", "Wiesmann",
                 "Xin Kai", "ZX", "ВАЗ", "Велта", "ГАЗ", "ЗАЗ", "ЗИЛ", "ИЖ", "КАМАЗ", "ЛУАЗ", "Москвич", "СеАЗ", "СМЗ",
                 "ТагАЗ", "УАЗ"]:
        TsMark.objects.create(name=mark)


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0021_tsmark'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
