# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_auto_20170301_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-date_created',), 'permissions': (('can_view_child', 'Может видеть заявки потомков'), ('can_view_all', 'Может видеть все заявки'), ('can_view_all_child', 'Может видеть все заявки своих агентов и агентов агентов'), ('can_card_search_mass', 'Может массово искать карты в еаисто'))},
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'Выполнена'), (3, 'Отменена'), (4, 'Изменена'), (5, 'Изменение отклонено'), (6, 'Дубликат'), (7, 'Удалена')], default=1, verbose_name='Статус'),
        ),
    ]
